- name: Emacs configuration files
  copy: src=files/emacs dest=/home/$user/.emacs

- name: Creates Emacs directory
  action: file path=/home/$user/.emacs.d state=directory

- name: Emacs .el files
  copy: src=$item dest=/home/$user/.emacs.d/
  with_fileglob:
    - files/*.el

- name: Creates Emacs themes directory
  action: file path=/home/$user/.emacs.d/themes state=directory

- name: Emacs theme
  copy: src=files/themes/zenburn-theme.el dest=/home/$user/.emacs.d/themes/